default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.23.6

images:
  - europe-west2-docker.pkg.dev/v2/k8s-artifacts-prod/images/kube-state-metrics/kube-state-metrics/manifests/v2.10.1
