default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.23.6

images:
  - registry.k8s.io/sig-storage/csi-resizer:v1.8.0
  - registry.k8s.io/sig-storage/csi-attacher:v4.3.0
  - registry.k8s.io/sig-storage/csi-provisioner:v3.5.0
  - registry.k8s.io/sig-storage/csi-snapshotter:v6.2.2
  - registry.k8s.io/sig-storage/csi-attacher:v4.3.0
  - registry.k8s.io/sig-storage/csi-provisioner:v3.5.0
  - registry.k8s.io/sig-storage/csi-resizer:v1.8.0
  - registry.k8s.io/sig-storage/csi-snapshotter:v6.2.2
