default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.23.6

images:
  - gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/webhook:v0.22.1
  - gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/controller:v0.22.1
  - gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/eventlistenersink:v0.22.1
  
